//选择
$(function(){
	//取消返回上一级
	$(".Select_btn_cancel").click(function(){
		window.location.href="serverelease.html";
	});
	//点击灰色区域
	$(".event_summary").click(function(){
		$(".event_summary").hide();
		$(".notes_overlook").hide();
	});
	//点击确定显示弹窗
	$(".Select_btn_confirm").click(function(){
		if($(this).hasClass("notes_btn_ok")){
			$(".event_summary").show();
			$(".notes_overlook").show();
		}
		if(!$(this).hasClass("notes_btn_ok")){
			$(".event_summary").hide();
			$(".notes_overlook").hide();
		}
	});
	//	点击弹窗取消按钮
	$(".notes_overlook_btnone").on("click",function(){
		$(".event_summary").hide();
		$(".notes_overlook").hide();
	});
	//多选
	$("li>em").attr("flage","true");
	$(".deleteparson_ul").on("click","li>em",function(){
		if($(this).attr("flage") == "true"){
			$(this).attr("flage","false");
			$(this).addClass("deleteparson_current");
			if($("em").hasClass('deleteparson_current')){
				$(".Select_btn_confirm").css("background","#6eabfe").addClass("notes_btn_ok");
			}
		}else{
			$(this).removeClass("deleteparson_current");
			$(this).attr("flage","true");
			if(!$("em").hasClass('deleteparson_current')){
				$(".Select_btn_confirm").css("background","#cecece").removeClass("notes_btn_ok");
			}
		}
	});
});
